return {
   transform     = require("src.components.transform"),
   body          = require("src.components.body"),
   grounded      = require("src.components.grounded"),
   collider      = require("src.components.collider"),
   sprite        = require("src.components.sprite"),
   controls      = require("src.components.controls"),
   inputResponse = require("src.components.inputResponse"),
   jumpForce     = require("src.components.jumpForce"),
   moveSpeed     = require("src.components.moveSpeed"),
   moveOnBeat    = require("src.components.moveOnBeat"),
   triggerable   = require("src.components.triggerable"),
   trigger       = require("src.components.trigger"),
   lit           = require("src.components.lit"),
   animation     = require("src.components.animation"),
   lightable     = require("src.components.lightable"),
}
